import Link from "next/link";
import { MediaSidebar } from "@/components/media-sidebar";
import { MovieCard } from "@/components/movie-card";
import { getStorefrontMovies } from "@/lib/movies";

type Props={searchParams:Promise<{q?:string;access?:string}>};
const categories=[{value:"all",label:"全部"},{value:"free",label:"免费"},{value:"subscription",label:"会员"},{value:"purchase",label:"单片购买"},{value:"subscription_or_purchase",label:"会员或购买"}];
export default async function Home({searchParams}:Props){const params=await searchParams;const q=(params.q??"").trim().toLowerCase();const access=params.access??"all";const movies=(await getStorefrontMovies()).filter(movie=>(access==="all"||movie.access===access)&&(!q||movie.title.toLowerCase().includes(q)||movie.description.toLowerCase().includes(q)));return <main className="home-main"><div className="home-layout"><MediaSidebar/><section className="home-feed"><div className="category-strip">{categories.map(category=>{const href=`/?access=${category.value}${q?`&q=${encodeURIComponent(q)}`:""}`;return <Link key={category.value} href={href} aria-current={access===category.value?"page":undefined}>{category.label}</Link>})}</div><div className="feed-heading"><div><p>HANABI PICKS</p><h1>{q?`“${q}” 的搜索结果`:"正在热播"}</h1></div><span>{movies.length} 部影片</span></div>{movies.length===0?<div className="empty-feed"><h2>没有找到影片</h2><p>尝试其他关键词或分类，或在管理后台发布影片。</p></div>:<div className="video-grid">{movies.map(movie=><MovieCard key={movie.id} movie={movie}/>)}</div>}</section></div><style jsx global>{`
.home-main{width:100%!important;max-width:none!important;margin:0!important;padding:0 24px 64px!important}.home-layout{display:grid;grid-template-columns:220px minmax(0,1fr);gap:28px;max-width:1700px;margin:0 auto}.home-feed{margin:0!important;padding:24px 0!important;border:0!important;background:transparent!important;box-shadow:none!important}.category-strip{display:flex;gap:10px;overflow-x:auto;padding-bottom:18px;scrollbar-width:none}.category-strip::-webkit-scrollbar{display:none}.category-strip a{flex:0 0 auto;padding:8px 14px;border-radius:8px;background:#272727;color:#f1f1f1;text-decoration:none;font-size:.9rem;font-weight:700}.category-strip a:hover{background:#3f3f3f}.category-strip a[aria-current="page"]{background:#f1f1f1;color:#0f0f0f}.feed-heading{display:flex;align-items:end;justify-content:space-between;gap:20px;margin:10px 0 24px}.feed-heading p{margin:0 0 5px;color:#ff3155;font-weight:900;letter-spacing:.14em;font-size:.75rem}.feed-heading h1{margin:0;font-size:clamp(1.7rem,3vw,2.6rem)}.feed-heading>span{color:#aaa}.video-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:32px 18px}.empty-feed{padding:70px 24px;text-align:center;border:1px solid #303030;border-radius:16px;background:#181818}.empty-feed h2{margin-top:0}@media(max-width:820px){.home-main{padding:0 14px 48px!important}.home-layout{display:block}.video-grid{grid-template-columns:repeat(auto-fill,minmax(240px,1fr))}.feed-heading{align-items:start}.feed-heading>span{padding-top:10px}}
`}</style></main>}
