"use client";
import Link from "next/link";
import { FavoriteButton } from "@/components/favorite-button";
import { formatCny } from "@/lib/cart";
import type { StorefrontMovie } from "@/lib/movies";
type Props={movie:StorefrontMovie;onRemoved?:()=>void};
const accessLabel={free:"免费",subscription:"会员",purchase:"单片购买",subscription_or_purchase:"会员或购买"};
export function MovieCard({movie,onRemoved}:Props){const detail=movie.priceCents>0?formatCny(movie.priceCents):movie.previewSeconds?`免费试看 ${Math.max(1,Math.round(movie.previewSeconds/60))} 分钟`:"会员可看";return <article className="video-card"><div className="video-thumb-wrap"><Link className="video-thumb" href={`/movies/${movie.id}`}>{movie.posterUrl?<img src={movie.posterUrl} alt={movie.title}/>:<span className="video-placeholder">HANABI</span>}<span className="video-access">{accessLabel[movie.access]}</span></Link><FavoriteButton movieId={movie.id} compact onRemoved={onRemoved}/></div><div className="video-card-info"><Link href={`/movies/${movie.id}`}><h3>{movie.title}</h3></Link><p>{movie.description||"HANABI 精选影片"}</p><span>{detail}</span></div><style jsx global>{`
.video-card{border:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;overflow:visible!important}.video-card:hover{transform:none!important;background:transparent!important;box-shadow:none!important}.video-thumb-wrap{position:relative}.video-thumb{position:relative;display:block;aspect-ratio:16/9;overflow:hidden;border-radius:12px;background:linear-gradient(135deg,#282828,#151515);text-decoration:none}.video-thumb img{display:block;width:100%!important;height:100%!important;margin:0!important;object-fit:cover}.video-placeholder{display:grid;height:100%;place-items:center;color:#777;font-size:1.25rem;font-weight:900;letter-spacing:.12em}.video-access{position:absolute;right:8px;bottom:8px;padding:4px 7px;border-radius:5px;background:rgba(0,0,0,.82);color:#fff;font-size:.75rem;font-weight:700}.favorite-button{position:absolute;right:8px;top:8px;display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:6px!important;width:auto!important;min-height:38px!important;padding:0 12px!important;border:0!important;border-radius:999px!important;background:rgba(15,15,15,.88)!important;color:#fff!important;box-shadow:none!important;font-size:1.1rem!important}.favorite-button:hover{background:#3f3f3f!important}.favorite-button[aria-pressed="true"]{color:#ff3155!important}.favorite-button.is-compact{width:38px!important;padding:0!important}.favorite-button:disabled{opacity:.65}.video-card-info{padding:12px 4px 0}.video-card-info a{text-decoration:none}.video-card-info h3{margin:0 0 6px;color:#f1f1f1;font-size:1rem;line-height:1.4}.video-card-info p{display:-webkit-box;overflow:hidden;margin:0 0 5px;color:#aaa;font-size:.88rem;line-height:1.4;-webkit-line-clamp:2;-webkit-box-orient:vertical}.video-card-info span{color:#aaa;font-size:.84rem}
`}</style></article>}
