import { createClient } from "@supabase/supabase-js";
export type VideoSource = "cloudflare_stream"|"supabase_storage";
export type StorefrontMovie = { id:string; title:string; description:string; posterUrl:string|null; access:"free"|"subscription"|"purchase"|"subscription_or_purchase"; priceCents:number; previewSeconds:number; videoSource:VideoSource; streamVideoUid:string|null; storageBucket:string|null; storagePath:string|null };
type MovieRow = { id:string; title:string; description:string; poster_url:string|null; access:StorefrontMovie["access"]; price_cents:number|null; preview_seconds:number; video_source:VideoSource; stream_video_uid:string|null; storage_bucket:string|null; storage_path:string|null };
function getClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false}}):null;}
function mapMovie(row:MovieRow):StorefrontMovie{return{id:row.id,title:row.title,description:row.description,posterUrl:row.poster_url,access:row.access,priceCents:row.price_cents??0,previewSeconds:row.preview_seconds,videoSource:row.video_source,streamVideoUid:row.stream_video_uid,storageBucket:row.storage_bucket,storagePath:row.storage_path};}
const fields="id, title, description, poster_url, access, price_cents, preview_seconds, video_source, stream_video_uid, storage_bucket, storage_path";
export async function getStorefrontMovies(){const client=getClient();if(!client)return[];const{data,error}=await client.from("movies").select(fields).eq("status","published").is("deleted_at",null).order("created_at",{ascending:false}).returns<MovieRow[]>();if(error){console.error("Unable to load movie catalogue",error);return[];}return data.map(mapMovie);}
export async function getStorefrontMovie(id:string){const client=getClient();if(!client)return null;const{data,error}=await client.from("movies").select(fields).eq("status","published").is("deleted_at",null).eq("id",id).maybeSingle<MovieRow>();return error||!data?null:mapMovie(data);}
