"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { MediaSidebar } from "@/components/media-sidebar";
import { MovieCard } from "@/components/movie-card";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import type { StorefrontMovie } from "@/lib/movies";
type MovieRow={id:string;title:string;description:string;poster_url:string|null;access:StorefrontMovie["access"];price_cents:number|null;preview_seconds:number;video_source:StorefrontMovie["videoSource"];stream_video_uid:string|null;storage_bucket:string|null;storage_path:string|null};
export default function FavoritesPage(){const router=useRouter();const [movies,setMovies]=useState<StorefrontMovie[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{const client=createSupabaseBrowserClient();if(!client){setLoading(false);return}void(async()=>{const{data:{user}}=await client.auth.getUser();if(!user){router.replace("/login");return}const{data:favorites}=await client.from("favorites").select("movie_id").eq("user_id",user.id).order("created_at",{ascending:false});const ids=(favorites??[]).map(item=>item.movie_id as string);if(ids.length===0){setLoading(false);return}const{data}=await client.from("movies").select("id,title,description,poster_url,access,price_cents,preview_seconds,video_source,stream_video_uid,storage_bucket,storage_path").in("id",ids).eq("status","published").is("deleted_at",null).returns<MovieRow[]>();const rows=data??[];setMovies(ids.map(id=>rows.find(row=>row.id===id)).filter((row):row is MovieRow=>Boolean(row)).map(row=>({id:row.id,title:row.title,description:row.description,posterUrl:row.poster_url,access:row.access,priceCents:row.price_cents??0,previewSeconds:row.preview_seconds,videoSource:row.video_source,streamVideoUid:row.stream_video_uid,storageBucket:row.storage_bucket,storagePath:row.storage_path})));setLoading(false)})()},[router]);return <main className="home-main"><div className="home-layout"><MediaSidebar/><section className="home-feed"><div className="feed-heading"><div><p>YOUR LIBRARY</p><h1>我的收藏</h1></div><span>{movies.length} 部影片</span></div>{loading?<div className="empty-feed"><p>正在加载收藏…</p></div>:movies.length===0?<div className="empty-feed"><h2>还没有收藏影片</h2><p>在首页点击影片卡片右上角的爱心即可收藏。</p></div>:<div className="video-grid">{movies.map(movie=><MovieCard key={movie.id} movie={movie} onRemoved={()=>setMovies(current=>current.filter(item=>item.id!==movie.id))}/>)}</div>}</section></div></main>}
